CREATE TABLE [dbo].[games] (
    [AppID]                   INT            NULL,
    [Name]                    VARCHAR (8000) NULL,
    [ReleaseDate]             VARCHAR (8000) NULL,
    [EstimatedOwners]         VARCHAR (8000) NULL,
    [PeakCCU]                 INT            NULL,
    [RequiredAge]             INT            NULL,
    [Price]                   FLOAT (53)     NULL,
    [DiscountDLCCount]        INT            NULL,
    [AboutTheGame]            INT            NULL,
    [SupportedLanguages]      VARCHAR (8000) NULL,
    [FullAudioLanguages]      VARCHAR (8000) NULL,
    [Reviews]                 VARCHAR (8000) NULL,
    [HeaderImage]             VARCHAR (8000) NULL,
    [Website]                 VARCHAR (8000) NULL,
    [SupportUrl]              VARCHAR (8000) NULL,
    [SupportEmail]            VARCHAR (8000) NULL,
    [Windows]                 VARCHAR (8000) NULL,
    [Mac]                     VARCHAR (8000) NULL,
    [Linux]                   BIT            NULL,
    [MetacriticScore]         VARCHAR (8000) NULL,
    [MetacriticUrl]           VARCHAR (8000) NULL,
    [UserScore]               VARCHAR (8000) NULL,
    [Positive]                VARCHAR (8000) NULL,
    [Negative]                VARCHAR (8000) NULL,
    [ScoreRank]               VARCHAR (8000) NULL,
    [Achievements]            VARCHAR (8000) NULL,
    [Recommendations]         INT            NULL,
    [Notes]                   VARCHAR (8000) NULL,
    [AveragePlaytimeForever]  VARCHAR (8000) NULL,
    [AveragePlaytimeTwoWeeks] INT            NULL,
    [MedianPlaytimeForever]   INT            NULL,
    [MedianPlaytimeTwoWeeks]  INT            NULL,
    [Developers]              VARCHAR (8000) NULL,
    [Publishers]              VARCHAR (8000) NULL,
    [Categories]              VARCHAR (8000) NULL,
    [Genres]                  VARCHAR (8000) NULL,
    [Tags]                    VARCHAR (8000) NULL,
    [Screenshots]             VARCHAR (8000) NULL,
    [Movies]                  VARCHAR (8000) NULL
);


GO

