CREATE TABLE [gold].[factgamescores] (

    [gameKey] varchar(8000) NULL,
    [pctIGDBRating] float NULL,
    [smoothedIGDBRating] float NULL,
    [IGDBSourceCount] bigint NULL,
    [totalReviews] bigint NULL,
    [sentimentReviews] bigint NULL,
    [avgPlaytimeAtReview] float NULL,
    [avgWordCount] float NULL,
    [avgEmotionalIntensity] float NULL,
    [pctPositiveSentiment] float NULL,
    [pctNeutralSentiment] float NULL,
    [pctNegativeSentiment] float NULL,
    [sentimentVoteAlignment] float NULL,
    [weightedSentiment] float NULL,
    [pctWeightedSentiment] float NULL,
    [weightedSentimentRating] float NULL,
    [weightedVote] float NULL,
    [pctWeightedVote] float NULL,
    [weightedVoteRating] float NULL,
    [pctVotedUp] float NULL,
    [voteRating] float NULL,
    [pctEarlyAccess] float NULL,
    [pctBugReports] float NULL,
    [pctRefunded] float NULL,
    [insert_run_id] varchar(8000) NULL,
    [update_run_id] varchar(8000) NULL,
    [hash] varchar(8000) NULL
);
