CREATE TABLE [gold].[factreviews] (

	[reviewKey] varchar(8000) NULL, 
	[gameKey] varchar(8000) NULL, 
	[reviewCleaned] varchar(8000) NULL, 
	[votedUp] bit NULL, 
	[votesUp] int NULL, 
	[votesFunny] int NULL, 
	[commentCount] int NULL, 
	[reactionCount] int NULL, 
	[communitySignal] real NULL, 
	[reviewLength] int NULL, 
	[wordCount] int NULL, 
	[wordLengthRatio] real NULL, 
	[uniqueWordRatio] real NULL, 
	[hasCredibleText] bit NULL, 
	[lengthSignal] real NULL, 
	[playtimeAtReview] int NULL, 
	[playtimeSignal] real NULL, 
	[isVaderEligible] bit NULL, 
	[sentimentCompound] real NULL, 
	[sentimentSignal] real NULL, 
	[sentimentDirection] int NULL, 
	[emotionalIntensity] real NULL, 
	[emotionalSignal] real NULL, 
	[voteDirection] int NULL, 
	[reviewInfluenceScore] real NULL, 
	[steamWeightedVoteScore] real NULL, 
	[refunded] bit NULL, 
	[writtenDuringEarlyAccess] bit NULL, 
	[containsBugReport] bit NULL, 
	[insert_run_id] varchar(8000) NULL, 
	[update_run_id] varchar(8000) NULL, 
	[hash] varchar(8000) NULL
);