version: 2

sources:
  - name: localSteam
    schema: main
    tables:
      - name: reviews
        config:
          meta:
            external_location: "{{ var('localSteam_reviews_path') }}"
            format: csv
      - name: games
        config:
          meta:
            external_location: "{{ var('localSteam_games_path') }}"
            format: csv
  - name: fabricSteam
    # database: SteamAnalytics
    schema: raw
    tables:
      - name: reviews
      - name: games